launch "env"
	test_launch 'cd ..' 'env -i cat auteur'
	test_launch 'env >/dev/null'
	test_launch 'cd ..' 'env -i cat auteur' 'env -i env -i cat auteur' 'env -i /usr/bin/env cat none'
	test_launch 'env -i none' 'NONE=cat' 'env -i $NONE auteur'
	test_launch 'env -i' 'env -i /bin/ls' 'env -i -- /bin/ls'
	test_launch 'env -i ls' 'env -i ls ls' 'env -i ""'
	test_launch 'env -i env' 'env -i env -i env' 'env >/dev/null' 'env TOTO=lol echo loltoto'
	test_launch 'env -- TOTO=lol echo stoplol'
	test_launch 'echo $TOTO'
	test_launch 'env -i TOTO=lol echo golol | grep golol' 'echo $TOTO'
	test_launch 'env "" "TOTO=popo=haha" /bin/ls'
	test_launch 'cd ..' 'env -i -- TOTO=plop cat auteur' 'echo $TOTO'
	test_launch 'cd ..' 'env -i TOTO=plop -- cat auteur' 'echo $TOTO'
	test_launch 'cd ..' 'env -iiiii cat auteur'
	test_launch 'cd ..' 'env -i -i -i TOTO=lol -i cat auteur'
	test_launch 'cd ..' 'env -i -i -i  -- TOTO=lol -i cat auteur'
	test_launch 'cd ..' 'env -i -i -i  -- TOTO=lol | grep TOTO='
	test_launch 'cd ..' 'env -i -i -i TOTO=lol | grep TOTO='
	test_launch 'cd ..' 'env -i -i -i TOTO=lol -i | grep TOTO='
	test_launch 'cd ..' 'env -i -i -i env TOTO=lol -i | grep TOTO='
	test_launch 'cd ..' 'env -i -i -i env TOTO=lol | grep TOTO='
